docs/betaseries.rst
docs/index.rst
docs/usage.rst
docs/workflows.rst
src/nibetaseries/cli/run.py

adds the graphing option specified in the api.

FIX: add graph

---

docs/conf.py
docs/workflows.rst
src/nibetaseries/workflows/analysis.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py

fixes #8 
Add workflow documentation and document the command line interface.

[ENH]: improve docs

---

MANIFEST.in
docs/requirements.txt
setup.cfg
setup.py
src/nibetaseries/cli/run.py
src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/workflows/analysis.py
src/nibetaseries/workflows/base.py

pass the current tests to get a baseline functionality

[FIX]: pass tests

---

CONTRIBUTING.rst

change jdkent to HBClab

---

README.rst

fixes #36
Add some useful introduction to the NiBetaSeries project so people know what's going on.

README (where's the beef?)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
MANIFEST.in

fixes #18 
Following the advice of [this blog](https://blog.github.com/2018-05-02-issue-template-improvements/) to complete creating templates.
This pull request replaces #42

Update issue templates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst
MANIFEST.in
docs/conf.py

Add pull request template

---

.travis.yml
setup.py
tox.ini

Adds a functional test on some made up data to test the workflows to make sure the code is syntactically correct.
Fixes #25 
- adds functional test to `tox.ini`

[TST]: Add functional test

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #46
- removed acknowledgments section of pull request template

removed acknowledgments section of pull request template

---

README.rst

Signed-off-by: Krista DeStasio <kdestasio@gmail.com>
Fixes #51
- Added a link to Contributing to NiBetaSeries under the Documentation in
the README file. 
- Also included a link to the issues page.

Add link to contributing in README

---

README.rst

Added underscores to line 97. 
Fixes #54 .
- Added underscores to line 97.

fix links in readme.rst

---

CONTRIBUTING.rst

Signed-off-by: Krista DeStasio <kdestasio@gmail.com>
Change the colors of issue labels in the CONTRIBUTING.rst file
to match the issue labels. Add issue labels to the CONTRIBUTING.rst
file if they were not already included.
Fixes # 45
- Change the colors of issue labels in the CONTRIBUTING.rst file
to match the issue labels. 
- Add issue labels to the CONTRIBUTING.rst
file if they were not already included.

Fix issue #45: conform colors of labels

---

README.rst

Signed-off-by: Krista DeStasio <kdestasio@gmail.com>
Add the link to the Zenodo DOI in the README.rst file.
Fixes #29 
- Add the link to the Zenodo DOI in the README.rst file.

Fix issue #29: Add link to Zenodo DOI

---

.zenodo.json
MANIFEST.in
tox.ini

Added the zenodo.json file (used the fmriprep one as ref), including info on the top 3 contributors. Happy to expand this list with the complete current list of contributors if you want. Couldn't run tox due to install issues on my end.
Fixes #59. 
I suggest what James suggested when creating the issue.

[DOC] Added zenodo file

---

docs/workflows.rst
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py
src/nibetaseries/workflows/utils.py

Fixes #73. 
This pull request makes it so we are collecting the repetition time of the bold series accurately (instead of it being hardcoded)
- change `collect_data` function to also collect the metadata
- propagate changes of `bold_info` to `bold_metadata` connect the parameter to the workflows.

[FIX]: Find metadata

---

src/nibetaseries/interfaces/nistats.py
src/nibetaseries/workflows/analysis.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/utils.py

a number of minor fixes when trying to run on a real dataset

various fixes for a real dataset

---

src/nibetaseries/interfaces/nistats.py

allows the confounds to be none in case no regressors are selected.

[ENH]: allow confounds to be none

---

CONTRIBUTING.rst
README.rst
docs/betaseries.rst
docs/workflows.rst
src/nibetaseries/cli/run.py
src/nibetaseries/interfaces/bids.py

Fixes #<NUM>. 
updates the documentation and help strings to (hopefully) be more informative and comprehensive.

[ENH] Reword docs

---

MANIFEST.in
setup.cfg
src/nibetaseries/cli/tests/test_run.py
src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_bids.py
src/nibetaseries/interfaces/tests/test_nilearn.py
src/nibetaseries/interfaces/tests/test_nistats.py
tests/test_nibetaseries.py
tox.ini

This pull request add tests to several of the interfaces being used in NiBetaSeries. (also changes how correlations are derived in AtlasCorrelations from Ledoit-Wolf to EmpiricalCovariance
Fixes #23 
Fixes #24 
Fixes #34  
- add test_nistats.py
- add test_nilearn.py
- add test_bids.py

[TST] Add more tests

---

setup.py
src/nibetaseries/cli/run.py

Fixes #80 
- add `--nthreads` option
- add `--use-plugin` option

[ENH] add nthreads option and make multiproc the default

---

src/nibetaseries/cli/run.py

Fixes #82 
- add comma  in `--hrf_model` option

[FIX] add missing comma in hrf_models

---

.travis.yml
MANIFEST.in
docs/conf.py
docs/index.rst
docs/requirements.txt
examples/README.txt
examples/plot_run_nibetaseries.py

Fixes #92. 
analyzes a subject from [ds000164](https://openneuro.org/datasets/ds000164/versions/00001)
- adds several dependencies to build docs
- adds example on how to use nibetaseries (calling the commandline through python)

[ENH] add example

---

.travis.yml
docs/conf.py

Fixes #<NUM>. 
Before I wasn't tracking the code version in the docs, this PR should fix that.

[FIX] track version with docs

---

docs/conf.py
docs/requirements.txt
tox.ini

Fixes #<NUM>. 
Gives the docs versions so people can look at older documentation

[ENH] add sphinx versioning

---

.travis.yml
docs/conf.py
docs/requirements.txt
examples/plot_run_nibetaseries.py

Fixes #<NUM>. 
The builds are taking close to an hour just because of the docs, this pull request should bring down the build time (after it is merged).

first pass at simplifying example

---

docs/conf.py

Fixes #<NUM>. 
build the master branch for docs again.

[FIX] add master back in to docs

---

README.rst

- fix pybids link in README.rst
Fixes #113.
- updates link to pybids

fix pybids link

---

examples/plot_run_nibetaseries.py

- adapt links to rst guidelines
Fixes #111.
- this PR adapts the link syntax to rst guidelines

fix syntax links

---

README.rst

* Add hyphens to "BIDS-compatible"
Yes I am a ridiculous pedant

DOC: Tiny tweak to README

---

README.rst
docs/betaseries.rst

Fixes #None. 
- clarify some documentation for readability

[DOC] edit docs

---

.travis.yml
requirements.txt
src/nibetaseries/conftest.py
src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/workflows/analysis.py
src/nibetaseries/workflows/base.py

ref #67 
Fixes #28 
Sorry about the mess @amandakeasson

[ENH] add visualizations

---

Dockerfile

Fixes #149 . 
- temporary fix to Dockerfile until miniconda is fixed.

[MAINT]: temporary fix to dockerfile

---

.circleci/config.yml
README.rst
examples/README.rst
examples/README.txt

Fixes #129 
- Use circleci to create a branch named `binder` on this repository and push the generated notebook to and `requirements.txt` file to that branch.
- point binderhub to that branch/file to build the notebook.
- link the binder notebook in several places in the text.

[ENH] add binder

---

.circleci/config.yml

Fixes #None. 
- since I leaned into calling "latest"->"unstable", I need to fix the [deploy](https://circleci.com/gh/HBClab/NiBetaSeries/84)

[MAINT] fix tagging/pushing docker images

---

README.rst
docs/FAQ.rst
docs/betaseries.rst
docs/installation.rst
docs/usage.rst
docs/workflows.rst
examples/README.rst

[DOC] Minor changes to documentation text

---

.readthedocs.yml
MANIFEST.in

Add the readthedocs yml file to specify what dependencies need to be installed for the documentation to build properly on readthedocs.
Fixes #172 . 
- Add the readthedocs yml file

[FIX] add readthedocs config file

---

setup.py

Fixes #161  
- adds pypiwin32 as an additional dependency if the operating system is windows.

[FIX] add pypiwin32 as conditional dependency

---

.joss/paper.md
.zenodo.json
.zenodo.tmp.json
CHANGELOG.rst

This pull request is the final checklist to make release v0.3.0.
Need to make sure the release follows the [instructions in the review](https://github.com/openjournals/joss-reviews/issues/1295#issuecomment-526328072)
requesting @PeerHerholz to approve being added as an author (and look over paper).

[REL] v0.3.0 release

---

.circleci/config.yml

Tags (e.g. v0.3.0) were not being built on circleci, this should change that behavior.
Fixes #None

[MAINT] build tags

---

MANIFEST.in
long_description.rst
pyproject.toml
scripts/README.md
scripts/create_long_description.py
scripts/generate_nibetaseries_images.sh
setup.cfg
setup.py
tox.ini

[MAINT] Change Installation Method

---

.joss/paper.md

Fixes #184. 
- Make paper more concise.

[DOC] address review comments

---

README.rst
docs/betaseries.rst
docs/usage.rst
docs/workflows.rst
examples/plot_run_nibetaseries.py
setup.cfg
src/nibetaseries/cli/run.py
src/nibetaseries/cli/tests/test_run.py
src/nibetaseries/conftest.py
src/nibetaseries/data/bids.json
src/nibetaseries/data/derivatives.json
src/nibetaseries/interfaces/bids.py
src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_bids.py
src/nibetaseries/workflows/analysis.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py
src/nibetaseries/workflows/tests/test_base.py
src/nibetaseries/workflows/tests/test_utils.py
src/nibetaseries/workflows/utils.py

Fixes #96. Fixes #26 
- generate more proper bids derivatives
- place the betaseries files themselves in the output directory
- only read fmriprep outputs greater than (v1.2.0)

[ENH,FIX] refactor bids file processing

---

.codecov.yml

Fixes #199. , ref #198
- add an explicit yml file for coverage settings

[MAINT] explicitly set codecov settings

---

.zenodo.json
docs/workflows.rst
src/nibetaseries/cli/run.py
src/nibetaseries/cli/tests/test_run.py
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_nistats.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py
src/nibetaseries/workflows/tests/test_base.py

Fixes #130. Fixes #196.
- Replace all uses of "low pass filter" with "high pass filter" in code and documentation.
- Fix a couple of typos in docs/workflows.rst.
- Add @tsalo to Zenodo file.

[FIX, DOC] Rename low-pass filter to high-pass filter

---

README.rst
docs/betaseries.rst
docs/workflows.rst
examples/plot_run_nibetaseries.py
src/nibetaseries/cli/run.py
src/nibetaseries/cli/tests/test_run.py
src/nibetaseries/conftest.py
src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_nistats.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py
src/nibetaseries/workflows/tests/test_base.py

Fixes None. References #197. 
- Add the `--estimator` argument to the CLI and all associated functions.
- Rename BetaSeries to LSSBetaSeries, along with associated input and output specs.
- Add LSABetaSeries (with associated input and output specs).
- Add LSA-specific tests.
P.S. slight refactor to fisher r to z transform Fixes #203

[ENH] Implement least squares- all (LSA) modeling

---

.joss/paper.md

Ref [this comment](https://github.com/openjournals/joss-reviews/issues/1295#issuecomment-530331054). 
- expand affiliations
- change several awkward phrases
- add funding sources for neurohackademy and michelle voss

[FIX] respond to suggested edits

---

src/nibetaseries/workflows/utils.py

Fixes #211 . 
- do not use regex_search=True
- fix 'description' -> 'desc' for actual use in the `.get` command

[FIX] use scope=derivatives in collect_data

---

.codecov.yml

[Reasonable pull requests are still failing](https://github.com/HBClab/NiBetaSeries/pull/205#issuecomment-531317459)
Fixes #None . 
- make codecov have a 70% target
- allow a single pull request to decrease coverage by 10%.
[Codecov Documentation](https://docs.codecov.io/docs/commit-status)

[MAINT] make codecov more lenient

---

.codecov.yml

Ref #215 
- this should actually fix codecov (I hope)

[FIX] make codecov yaml valid

---

.travis.yml

Fixes #190. 
- separate code coverage from matrix
- add deploy as another stage

[MAINT] make travisci more efficient

---

CHANGELOG.rst

Fixes #208 
- add title to changelog
- make the versions sub-headings

[FIX,DOC] make title for changelog

---

.codecov.yml

Fixes #None. 
- [reasonable pull request still getting flagged](https://codecov.io/gh/HBClab/NiBetaSeries/compare/0bd10a139c2636fdfc3c3c69c625ff4e4c909e30...a457fa957cac48effe6d359b2f1142595e8ec94a)

[MAINT] allow more lenience for pull requests

---

docs/workflows.rst

Fixes #224 . 
- add `img.nii.gz` and `lut.tsv` to workflow.

[DOC,FIX] add fake img and lut to participant workflow

---

README.rst

[DOC] add joss badge

---

docs/workflows.rst

- add sub-headings
- change least squares to least squares-
Fixes #230 . 
- add documentation about LSA in workflows.rst

[DOC] add lsa section

---

Dockerfile_devel
docs/installation.rst

[FIX] add nano to dev container

---

examples/plot_run_nibetaseries.py

[DOC] Clarify in demo that you are stripping color codes #123

---

Dockerfile_devel

Fixes #237. 
- update code-server version in Dockerfile_devel to a currently existing (non-preview) release.

[FIX] update code-server version

---

setup.cfg
src/nibetaseries/interfaces/nistats.py

Fixes #244 . 
- set nistats version to 0.0.1b1
- update api (period_cut to high_pass)

[MAINT] fix nistats dependency 

---

setup.cfg
src/nibetaseries/workflows/tests/test_base.py
src/nibetaseries/workflows/utils.py

[ENH] create useful error message when images are not found 

---

.travis.yml
src/nibetaseries/cli/tests/test_run.py

Increases testing coverage for `run.py`
- use parametrize and monkeypatch instead of subprocess
- test another expected error.

[MAINT] refactor and increase tests for run.py

---

CHANGELOG.rst
long_description.rst

[REL] v0.4.1rc1

---

src/nibetaseries/cli/run.py
src/nibetaseries/cli/tests/test_run.py

Fixes #258 . 
- strip `sub-` from inputs to `--participant-label`

[FIX] allow "sub-" prefix

---

src/nibetaseries/cli/run.py
src/nibetaseries/conftest.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/tests/test_base.py
src/nibetaseries/workflows/tests/test_utils.py
src/nibetaseries/workflows/utils.py

Fixes #252 . 
- add `--database-path` option
- only index bold metadata

[ENH] improve bids indexing

---

src/nibetaseries/interfaces/nistats.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/tests/test_base.py

Fixes #261  
- remove minimum length check in nistats interface
- add length check if correlations are being generated
- test the length check function

[FIX] less strict beta map generation

---

src/nibetaseries/cli/run.py
src/nibetaseries/workflows/base.py

Fixes #268. 
- remove restriction on output space user can choose.

[FIX] allow other spaces

---

docs/FAQ.rst
docs/usage.rst
examples/plot_run_nibetaseries.py

Fixes #263 . 
- updates tutorial
- adds use case
- adds entry to faq

[DOC] emphasize beta map analysis

---

src/nibetaseries/workflows/tests/test_utils.py
src/nibetaseries/workflows/utils.py

Fixes #None. 
- raise an error to say what type of file is missing instead of a vague error message about bids structure.

[FIX] Better error message for missing files

---

CHANGELOG.rst
long_description.rst

[REL] v0.4.2rc1

---

src/nibetaseries/interfaces/nilearn.py
src/nibetaseries/interfaces/tests/test_nilearn.py
src/nibetaseries/workflows/base.py

Fixes #276 . 
- add CensorVolumes interface to remove presumably artefactual beta volumes before doing correlations.

[ENH] censor invalid volumes

---

setup.cfg

Fixes #279. 
change minimum nipype version to v1.4.2

[FIX] bump nipype version

---

CHANGELOG.rst
long_description.rst

[REL] v0.4.3rc1

---

src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_nistats.py

Fixes #290 . 
- add ability to pass python nifti objects into LSS and LSA interfaces.

[ENH] Allow niftiimage input

---

src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_nistats.py

Fixes #295 . 
- add function corresponding to [Calhoun 2004](https://s3.amazonaws.com/academia.edu.documents/44837983/FMRI_analysis_with_the_general_linear_mo20160417-21120-11k2292.pdf?response-content-disposition=inline%3B%20filename%3DfMRI_analysis_with_the_general_linear_mo.pdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWOWYYGZ2Y53UL3A%2F20200309%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200309T224911Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=3ddc994ea06c7ec20b35b79f6677da07f3e8aab9feedbc3ca5fcd68fe802530f)
- test the function with different hrf_models

[ENH,FIX] optimally combine temporal + dispersion derivatives for beta estimation

---

docs/workflows.rst
src/nibetaseries/cli/run.py
src/nibetaseries/cli/tests/test_run.py
src/nibetaseries/interfaces/nistats.py
src/nibetaseries/interfaces/tests/test_nistats.py
src/nibetaseries/workflows/base.py
src/nibetaseries/workflows/model.py
src/nibetaseries/workflows/tests/test_base.py

Fixes #281 . 
- add `--normalize-betas` option

[ENH] add --normalize-betas option

---

.zenodo.json
CHANGELOG.rst
long_description.rst

[REL] v0.5.0rc1

---

.travis.yml
.zenodo.json
CHANGELOG.rst
long_description.rst

(hopefully) fix the secure password error from travis-ci.

[REL] v0.5.0rc2

---

CHANGELOG.rst
long_description.rst

[REL] v0.6.0rc1

---

.travis.yml

Fixes #329 . 
- change from python 3.5 to 3.6 in travis build

[MAINT/DOC] change python version to 3.6 to build docs

---

setup.cfg

Fixes #332 . 
- pin sklearn version to ~0.22.0

[MNT] fix sklearn installation in py3.8

---

setup.cfg

Fixes #335 . 
- keep the bibtex extension below 2.0.0

[FIX] keep bibtex below major release 2.0.0

---

.travis.yml

[MAINT] update from xenial to bionic
